spring:
  application:
    name: shortener-url
  datasource:
    url: jdbc:postgresql://localhost:15432/shortener_db
    username: postgres
    password: postgres

  jpa:
    show-sql: true

  docker:
    compose:
      lifecycle-management: start_only
