spring:
  application:
    name: demo

  # Enable Content Negotiation
  mvc:
    contentnegotiation:
      default-content-types: application/json
      favor-parameter: true
      favor-path-extension: true
