### Create a new product
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "iPhone 17",
  "description": "iPhone 17 new version",
  "price": "1500.00",
  "productType": "phone"
}

### Edit product
PUT http://localhost:8080/products/5
Content-Type: application/json

{
  "name": "Notebook",
  "description": "College-ruled paper notebook modified",
  "price": "6.0",
  "productType": "stationery"
}

### Get products
GET http://localhost:8080/products/filter

### Get all products
GET http://localhost:8080/products?format=xml