services:
  postgres:
    image: 'postgres:18.1-alpine'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=shortener_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '15432:5432'
